### ISSUE TITLE
CCode 1.8 - GUI Issues

### ISSUE THREAD

**Issue by bovirus** [dvdforge/ccode_translations#3]
@dvdforge 

Please check screenshots

**Screenshot 01**

![image](https://github.com/dvdforge/ccode_translations/assets/1262554/6262869c-04b5-45b3-b466-c903ca48c291)

Onn top elft I didn't find the string in language file.

On bottom right tehre three strings untranslated.
Pelase add them to language files

**Screenshot 02**

![image](https://github.com/dvdforge/ccode_translations/assets/1262554/19a12ed4-09ad-4af2-9437-ab48cc384ec1)

I tranbslated the fiel filter and it saved in ccode.ini

[CCode]
Config1=39883680
Config2=1092
ZoomLevel=0
SearchFlags=34
Left=570
Right=1413
Bottom=800
Top=220
ShowCmd=3
LeftTabWidth=429
BottomTabHeight=200
BuildToolId=0
Path=::{20D04FE0-3AEA-1069-A2D8-08002B30309D}
ViewMode=3
ViewFlags=1075838980
IconSize=16
Filter=All Files (*.*)
Lang=ITA
[Filter]
Tutti i file (*.*)
File C/C++ (*.cpp;*.c;*.h;*.cxx;*.hxx;*.rc)
File web (*.html;*.htm;*.jsp;*.php;*.js;*.css;*.xml)
File Java (*.java)

but after re-run the program it shoiwed themn in english.

I propse to move the four strinms of filetr in language files.

**Comment by imgdrive** [comment]
Have moved some strings to .ini: https://yubsoft.com/ccode/lang_changes_1.9.html

**Comment by bovirus** [comment]
@dvdforge 
Thanks.
Where can I get CCode 1.9?

**Comment by imgdrive** [comment]
https://www.yubsoft.com/news?id=61

**Comment by bovirus** [comment]
@dvdforge 

GUI Issues (version 1.9 BETA 1)

![image](https://github.com/dvdforge/ccode_translations/assets/1262554/6e093b26-8737-46f5-b645-b6a498c033e2)

"Lingua" (Language) as caption is not right. 
Add a separete struing for it in language file.

Some file types should be translated (es. see red boxes).
Please add relative strings in language files.


![image](https://github.com/dvdforge/ccode_translations/assets/1262554/384e99b2-49ab-4a3a-a21d-1fc167600c29)

The drop down width is not enough. Please increase it.
Please add the items highlighted in language file to enable atranslation without to change ini file.


![image](https://github.com/dvdforge/ccode_translations/assets/1262554/bf68a223-0484-46e7-a37a-ee38c0dbb659)

Add string "Shift" used in menu in language file.
Add strings like "BARRA SPAZIATRICE", "CANCELLA", in language file.
Hot key "CTRL+ù" is not so easy.

Flag indicator INS/OVR (bottom right) is in english.
Please add "INS" and "OVR" strings in language file.

**Comment by bovirus** [comment]
@dvdforge 

Could be possible to enable OS language and set automatic CCode language (if available)?
Ex. OS Italian - CCode start in italian.

**Comment by imgdrive** [comment]
> Could be possible to enable OS language and set automatic CCode language (if available)?
> Ex. OS Italian - CCode start in italian.

Yes, it's possible, very good advice.

**Comment by bovirus** [comment]
@dveforge

Please check GUI issues.
And if you can please fix before release 1.9 final version.

**Comment by imgdrive** [comment]
> @dvdforge
> 
> GUI Issues (version 1.9 beta 1)
> 
> ![image](https://user-images.githubusercontent.com/1262554/247114101-6e093b26-8737-46f5-b645-b6a498c033e2.png)
> 
> "Lingua" (Language) as caption is not right. Add a separete struing for it in language file.
> 
> Some file types should be translated (es. see red boxes). Please add relative strings in language files.
> 
> ![image](https://user-images.githubusercontent.com/1262554/247114485-384e99b2-49ab-4a3a-a21d-1fc167600c29.png)
> 
I've noted this issue, will improve it future.
> The drop down width is not enough. Please increase it. Please add the items highlighted in language file to enable atranslation without to change ini file.
> 
> ![image](https://user-images.githubusercontent.com/1262554/247116053-bf68a223-0484-46e7-a37a-ee38c0dbb659.png)
> 
v1.9 had added "%s Files", please exit ccode, remove [Filter] section in ccode.ini, then restart ccode.
>
> Add string "Shift" used in menu in language file. Add strings like "BARRA SPAZIATRICE", "CANCELLA", in language file. Hot key "CTRL+ù" is not so easy.
> 
The "BARRA SPAZIATRICE", "CANCELLA" are from Windows API https://learn.microsoft.com/en-us/windows/win32/api/winuser/nf-winuser-getkeynametextw
> Flag indicator INS/OVR (bottom right) is in english. Please add "INS" and "OVR" strings in language file.
>
Had updated language file with INS/OVR.

**Comment by bovirus** [comment]
@dvdforge 

In keyboard the key in "CANC" not "CANCELLA":
But is also MS made an error it's  a nightmare.

Please update CCode application (INS/OVR are translated but appear always in english).
Please increase drop down with about file type on top left.

**Comment by imgdrive** [comment]
> @dvdforge
> 
> In keyboard the key in "CANC" not "CANCELLA": But is also MS made an error it's a nightmare.
>
Maybe need do some workaround, I'll install Italian language to win11 machine to check this issue.
> 
> Please update CCode application (INS/OVR are translated but appear always in english). Please increase drop down with about file type on top left.
Done. https://www.yubsoft.com/news?id=61

**Comment by bovirus** [comment]
@dvdforge 

GUI issues 1.9.0 beta 2

"Load session" or "Save session" window

![image](https://github.com/dvdforge/ccode_translations/assets/1262554/f21cd092-9a80-404c-ad93-c804bf7f1bda)

Untranslated strings (File type)

![image](https://github.com/dvdforge/ccode_translations/assets/1262554/6e093b26-8737-46f5-b645-b6a498c033e2)

"Lingua" (Language) as caption is not right. 
Add a separete string for this specifc caption in language file.

Some file types should be translated (es. see red boxes).
Please add relative strings in language files.

**Comment by imgdrive** [comment]
@bovirus 
done: 
![image](https://github.com/dvdforge/ccode_translations/assets/19568093/b0eabea3-b8f2-42aa-b687-5eea0d13d908)

to do in future:
![image](https://github.com/dvdforge/ccode_translations/assets/19568093/82a0d5f1-a538-424f-98e0-358e711ddd21)

**Comment by imgdrive** [comment]
https://www.yubsoft.com/news?id=61

**Comment by bovirus** [comment]
@dvdforge 

The new program link point to beta 3 but in the page is mentioned as beta2.

#################################################

![image](https://github.com/dvdforge/ccode_translations/assets/1262554/c90a4ef9-eba5-476b-8729-f50c3c4eb678)

Please enlarge window width
Please enlarge text width for "Corrispondenza maisucole/minusciole"

#################################################

![image](https://github.com/dvdforge/ccode_translations/assets/1262554/6b9736e1-4028-459d-b309-6cc430c85672)

The strings highlighted are untranslated.
Please add them to language files.

#################################################

![image](https://github.com/dvdforge/ccode_translations/assets/1262554/a0c56889-494d-40e0-8ae6-88d93b585128)

Please fix a if you can for "CANCELLA" (should be "CANC")
Please add "Shift" in languafe file and use it.

**Comment by imgdrive** [comment]
https://www.yubsoft.com/ccode/

1. Had enlarged the find/replace/find in files dialog.
2. The strings highlighted are untranslated.
Oh, you need remove the old filters in ccode.ini.
3. I will think a better method to solve this issue, leave to version 2.0 :)

Thank you for your feedback.

**Comment by bovirus** [comment]
Ok. Please close this issue.
