### ISSUE TITLE
Language version

### ISSUE THREAD

**Issue by bovirus** [dvdforge/ccode_translations#5]
@dvdforge 

It seems that the info on home page relating language version are not updated.

Italian language version seems v. 2.1 (not 2.0).
Turkish version seems version 1.6 (not 1.8).

**Comment by imgdrive** [comment]
Fixed "Italian language version seems v. 2.1 (not 2.0)."

I had checked the email, the Turkish version is 1.8, had updated CCode_TRK.ini to 1.8.

Thank you.

**Comment by bovirus** [comment]
Thanks.
